# 1. Use an official Node.js image
FROM node:20-alpine

# 2. Set working directory inside container
WORKDIR /app

# 3. Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# 4. Copy the rest of the app
COPY . .

# 5. Expose the port (your app runs on 3000)
# EXPOSE 3001

# 6. Command to run app with nodemon
CMD ["npm", "run", "start"]
